# Generated by Django 5.2.7 on 2025-12-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='to_notify',
            field=models.BooleanField(default=False),
        ),
    ]
